// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CheckValidPassword struct {
	NoMatch []*string `json:"noMatch"`
	Verify  *bool     `json:"verify"`
}

type Rule struct {
	Rule  string `json:"rule"`
	Value int    `json:"value"`
}

type RuleInput struct {
	Rule  *string `json:"rule"`
	Value *int    `json:"value"`
}
